package com.simchat.shared.dataclasses;

public enum MessageType {
    LOGIN_MESSAGE, SIGNUP_MESSAGE, STANDART_MESSAGE, ADD_FRIEND, RETURN_FRIENDLIST, SERVER_OK,
    SERVER_ERROR, RETURN_MESSAGES_BETWEEN_USERS
}
