package com.simchat.server;
import com.simchat.shared.dataclasses.Message;
import com.simchat.shared.dataclasses.MessageType;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

import static com.simchat.server.ServerMain.*;

/**
 * Class used to communicate with database server. Implements method for creating tables, adding data to table.
 * or selecting data from table. Also implements hash of password. Used in ClientHandler.
 */
public class Database {

    /**
     * connection to database
     */
    protected Connection connection;

    /**
     * Create connection to database based on static variables from ServerMain.
     * @throws SQLException if can´t create connection.
     */
    public Database() throws SQLException {
        connection = DriverManager.getConnection(url+"/"+nameOfDatabase, databaseUser, databasePassword);
    }

    /**
     * Method to check combination of username and password, if it is stored in database.
     * @param username username to be checked.
     * @param password password to be checked.
     * @throws SQLException if can´t communicate with database.
     * @return true if username with this password is stored in database.
     */
    public boolean checkUsernameAndPassword(String username, String password) throws SQLException {
        PreparedStatement preparedStatement = connection.prepareStatement("SELECT * FROM users WHERE username = ? ");
        preparedStatement.setString(1, username);
        ResultSet resultSet =  preparedStatement.executeQuery();
        if(resultSet.next()){
            byte[] hashedPassword = resultSet.getBytes(2);
            byte[] salt = resultSet.getBytes(3);
            byte[] hashedPasswordToCompare = hashPassword( password, salt);
            if(Arrays.equals(hashedPassword,hashedPasswordToCompare)){
                return true;
            }
        }
        return false;
    }

    /**
     * Hashing method of password, using SHA-512 hash and randomly generated bytes (salt) to be added to password.
     * before hash to make it stronger.
     * @param password password to be hashed.
     * @param salt randomly generated bytes to be added to password.
     * @return array of bytes which contains hashed (password+salt).
     */
    private byte[] hashPassword(String password, byte[]salt){
        MessageDigest md = null;
        try {
            md = MessageDigest.getInstance("SHA-512");
        } catch (NoSuchAlgorithmException e) {
            System.out.println("[ERROR] Cannot hash password!");
            e.printStackTrace();
            throw new RuntimeException(e);
        }
        md.update(salt);
        return md.digest(password.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Add user to database. Generate random bytes (salt) for stronger hashing, hash password with that salt and then.
     * store username, hashed password, salt to database.
     * @param username username to be added to database.
     * @param password password to be added to database.
     * @throws SQLException if can´t communicate with database or insert.
     */
    public void addUser(String username, String password) throws SQLException {

        //hash password
        byte[] salt = new byte[16];
        SecureRandom random = new SecureRandom();
        random.nextBytes(salt);
        byte[] hashedPassword = hashPassword(password, salt);

        PreparedStatement preparedStatement =  connection.prepareStatement("INSERT INTO users VALUES (?,?,?)");
        preparedStatement.setString(1, username);
        preparedStatement.setBytes(2, hashedPassword);
        preparedStatement.setBytes(3, salt);
        preparedStatement.executeUpdate();

        createTableUserFriendList(username);
        createTableUserMessages(username);
    }

    /**
     * Request to database, if username is stored there.
     * @param username username to be checked if is stored in database.
     * @return true if username is stored in database.
     * @throws SQLException if can´t communicate with database.
     */
    public boolean userExists(String username) throws SQLException {
        PreparedStatement preparedStatement = connection.prepareStatement("SELECT * FROM users WHERE username = ?");
        preparedStatement.setString(1, username);
        ResultSet resultSet =  preparedStatement.executeQuery();
        if(resultSet.next()){
            return true;
        }
        return false;
    }

    /**
     * Add one user (friendUserName) to other user friendlist (username).
     * @param username user, which friendlist will be updated.
     * @param friendUserName used, which will be stored in friendlist.
     * @throws SQLException if can´t communicate with database or insert.
     */
    public void addFriend(String username, String friendUserName) throws SQLException {
        PreparedStatement preparedStatement =  connection.prepareStatement("INSERT INTO "+username+"_friendlist VALUES (?)");
        preparedStatement.setString(1, friendUserName);
        preparedStatement.executeUpdate();
    }

    /**
     * Findout if one user (senderUsername) is in friendlist of other user (receiverUsername).
     * @param senderUsername user, which will be looked up in friendlist.
     * @param receiverUsername user, which friendlist is searched.
     * @return true if senderUsername is in receiverUsername friendlist.
     * @throws SQLException if can´t communicate with database.
     */
    public boolean isFriendOfSender(String senderUsername, String receiverUsername) throws SQLException {
        PreparedStatement preparedStatement =  connection.prepareStatement("SELECT * FROM "+receiverUsername+"_friendlist WHERE username=?");
        preparedStatement.setString(1, senderUsername);
        ResultSet resultSet = preparedStatement.executeQuery();
        ArrayList<String> friends = new ArrayList<>();
        while(resultSet.next()){
            return true;
        }
        return false;
    }

    /**
     * Receive friendlist of user(username).
     * @param username user, which friendlist will be received.
     * @return list of friends of username.
     * @throws SQLException if can´t communicate with database.
     */
    public ArrayList<String> getFriends(String username) throws SQLException {
        PreparedStatement preparedStatement =  connection.prepareStatement("SELECT * FROM "+username+"_friendlist");
        ResultSet resultSet = preparedStatement.executeQuery();
        ArrayList<String> friends = new ArrayList<>();
        while(resultSet.next()){
            friends.add(String.valueOf(resultSet.getString(1)));
        }
        return friends;
    }

    /**
     * Create table friendlist of user (username) in database. Used when creating new user in database.
     * @param username user which friendlist will be created.
     * @throws SQLException if can´t communicate with database.
     */
    public void createTableUserFriendList(String username) throws SQLException {
           connection.prepareStatement("CREATE TABLE "+username+"_friendlist (username VARCHAR(50) UNIQUE, PRIMARY KEY(username))").execute();
    }

    /**
     * Create table (blank) with messages from/to this user.
     * @param username user which message list will be created.
     * @throws SQLException if can´t communicate with database.
     */
    public void createTableUserMessages(String username) throws SQLException {
            connection.prepareStatement("CREATE TABLE "+username+"_messages (ID INTEGER NOT NULL AUTO_INCREMENT," +
                    "fromUser VARCHAR(50),toUser VARCHAR(50)," +
                    "datetime DATETIME,message TEXT, PRIMARY KEY(ID))").execute();
    }

    /**
     * Convert java DateTime to database type of storing date time.
     * @param createdTime Java type DateTime which will be converted.
     * @return converted date time in database format.
     */
    private String dateTimeToDatabaseDate(LocalDateTime createdTime) {
        return String.valueOf(createdTime).replace('T',' ');
    }

    /**
     * Convert database type of storing data time to java type DateTime.
     * @param date date in database format which will be converted.
     * @return converted date time in java format.
     */
    private LocalDateTime databaseDateToDateTime(String date) {
        LocalDateTime dateTime =  LocalDateTime.parse(date.replace(' ','T'));
        return dateTime;
    }

    /**
     * Insert message in database. Insertion is done to messages table of both sender and receiver.
     * @param fromUser user who send message.
     * @param toUser user who receives message.
     * @param messageToSend payload, message which user wrote.
     * @param createdTime creation of message.
     * @throws SQLException if can´t communicate with database or insert.
     */
    public void insertMessage(String fromUser, String toUser, String messageToSend, LocalDateTime createdTime) throws SQLException {
        String databaseDateFormat = dateTimeToDatabaseDate(createdTime);
        PreparedStatement preparedStatement =  connection.prepareStatement("INSERT INTO "+fromUser+"_messages " +
                "(fromUser, toUser,datetime,message) VALUES (?,?,?,?)");
        preparedStatement.setString(1, fromUser);
        preparedStatement.setString(2, toUser);
        preparedStatement.setString(3, databaseDateFormat);
        preparedStatement.setString(4, messageToSend);
        preparedStatement.executeUpdate();

        preparedStatement =  connection.prepareStatement("INSERT INTO "+toUser+"_messages " +
                "(fromUser, toUser,datetime,message) VALUES (?,?,?,?)");
        preparedStatement.setString(1, fromUser);
        preparedStatement.setString(2, toUser);
        preparedStatement.setString(3, databaseDateFormat);
        preparedStatement.setString(4, messageToSend);
        preparedStatement.executeUpdate();

    }

    /**
     * Select list of messages between two users from fromUser messagelist from database and return it.
     * @param fromUser user from whose messagelist on database will be selected.
     * @param toUser user to whom/from messages will be selected in fromUser messagelist .
     * @return list of messages between fromUser and toUser.
     * @throws SQLException if can´t communicate with database.
     */
    public ArrayList<Message> getMessagesBetweenUsers(String fromUser, String toUser) throws SQLException {
        PreparedStatement preparedStatement =  connection.prepareStatement("SELECT * FROM "+fromUser+"_messages WHERE (fromUser=? AND toUser=?) OR (fromUser=? AND toUser=?)");
        preparedStatement.setString(1, fromUser);
        preparedStatement.setString(2, toUser);
        preparedStatement.setString(3, toUser);
        preparedStatement.setString(4, fromUser);
        ResultSet resultSet = preparedStatement.executeQuery();
        ArrayList<Message> messages = new ArrayList<>();
        while(resultSet.next()){
            LocalDateTime dateTime= databaseDateToDateTime(String.valueOf(resultSet.getString(4)));
            String from,to,message;
            from = String.valueOf(resultSet.getString(2));
            to=String.valueOf(resultSet.getString(3));
            message = String.valueOf(resultSet.getString(5));
            messages.add(new Message(MessageType.STANDARD_MESSAGE, from, to,dateTime, message));
        }
        return messages;
    }

}